interface ZIF_C_HR231_DEFAULTSEDIT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_HR231_DEFAULTSEDIT,
 CREATE_ZC_HR231_DEFAULTSEDIT   TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE3C16F',
 DELETE_ZC_HR231_DEFAULTSEDIT   TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE4416F',
 LOCK_ZC_HR231_DEFAULTSEDIT     TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE3016F',
 SAVE_ZC_HR231_DEFAULTSEDIT     TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE4C16F',
 UNLOCK_ZC_HR231_DEFAULTSEDIT   TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE3416F',
 UPDATE_ZC_HR231_DEFAULTSEDIT   TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE4016F',
 VALIDATE_ZC_HR231_DEFAULTSEDIT TYPE /BOBF/ACT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE4816F',
      END OF ZC_HR231_DEFAULTSEDIT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_HR231_DEFAULTSEDIT,
        BEGIN OF LOCK_ZC_HR231_DEFAULTSEDIT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_HR231_DEFAULTSEDIT,
        BEGIN OF UNLOCK_ZC_HR231_DEFAULTSEDIT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_HR231_DEFAULTSEDIT,
      END OF ZC_HR231_DEFAULTSEDIT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_HR231_DEFAULTSEDIT,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE5A16F',
      END OF ZC_HR231_DEFAULTSEDIT,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_HR231_DEFAULTSEDIT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2E16F',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2A16F',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE3A16F',
      END OF ZC_HR231_DEFAULTSEDIT,
      BEGIN OF ZC_HR231_DEFAULTSEDIT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE5216F',
      END OF ZC_HR231_DEFAULTSEDIT_LOCK,
      BEGIN OF ZC_HR231_DEFAULTSEDIT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE5016F',
      END OF ZC_HR231_DEFAULTSEDIT_MESSAGE,
      BEGIN OF ZC_HR231_DEFAULTSEDIT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE5416F',
      END OF ZC_HR231_DEFAULTSEDIT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_HR231_DEFAULTSEDIT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_HR231_DEFAULTSEDIT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2016F' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_HR231_DEFAULTSEDIT' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_HR231_DEFAULTSEDIT          TYPE /BOBF/OBM_NODE_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2416F',
 ZC_HR231_DEFAULTSEDIT_LOCK     TYPE /BOBF/OBM_NODE_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2C16F',
 ZC_HR231_DEFAULTSEDIT_MESSAGE  TYPE /BOBF/OBM_NODE_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2816F',
 ZC_HR231_DEFAULTSEDIT_PROPERTY TYPE /BOBF/OBM_NODE_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE3816F',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_HR231_DEFAULTSEDIT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PERNR                          TYPE STRING VALUE 'PERNR',
  EMERGROLE_ID                   TYPE STRING VALUE 'EMERGROLE_ID',
  KZ                             TYPE STRING VALUE 'KZ',
  EN                             TYPE STRING VALUE 'EN',
  RU                             TYPE STRING VALUE 'RU',
      END OF ZC_HR231_DEFAULTSEDIT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_HR231_DEFAULTSEDIT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '2D2184AB98EA1EDDAF8949EC8AE2616F',
      END OF ZC_HR231_DEFAULTSEDIT,
    END OF SC_NODE_CATEGORY .
endinterface.
