interface ZIF_C_HR231_DEFAULTS_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_HR231_DEFAULTS,
 CREATE_ZC_HR231_DEFAULTS       TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C430E1A',
 DELETE_ZC_HR231_DEFAULTS       TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C438E1A',
 LOCK_ZC_HR231_DEFAULTS         TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C424E1A',
 SAVE_ZC_HR231_DEFAULTS         TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C440E1A',
 UNLOCK_ZC_HR231_DEFAULTS       TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C428E1A',
 UPDATE_ZC_HR231_DEFAULTS       TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C434E1A',
 VALIDATE_ZC_HR231_DEFAULTS     TYPE /BOBF/ACT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C43CE1A',
      END OF ZC_HR231_DEFAULTS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_HR231_DEFAULTS,
        BEGIN OF LOCK_ZC_HR231_DEFAULTS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_HR231_DEFAULTS,
        BEGIN OF UNLOCK_ZC_HR231_DEFAULTS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_HR231_DEFAULTS,
      END OF ZC_HR231_DEFAULTS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_HR231_DEFAULTS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '495EFABCCEFB1EDDABD4A5E1C53D8E1A',
      END OF ZC_HR231_DEFAULTS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_HR231_DEFAULTS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C422E1A',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C41EE1A',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C42EE1A',
      END OF ZC_HR231_DEFAULTS,
      BEGIN OF ZC_HR231_DEFAULTS_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C446E1A',
      END OF ZC_HR231_DEFAULTS_LOCK,
      BEGIN OF ZC_HR231_DEFAULTS_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C444E1A',
      END OF ZC_HR231_DEFAULTS_MESSAGE,
      BEGIN OF ZC_HR231_DEFAULTS_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C448E1A',
      END OF ZC_HR231_DEFAULTS_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_HR231_DEFAULTS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_HR231_DEFAULTS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C414E1A' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_HR231_DEFAULTS' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_HR231_DEFAULTS              TYPE /BOBF/OBM_NODE_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C418E1A',
 ZC_HR231_DEFAULTS_LOCK         TYPE /BOBF/OBM_NODE_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C420E1A',
 ZC_HR231_DEFAULTS_MESSAGE      TYPE /BOBF/OBM_NODE_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C41CE1A',
 ZC_HR231_DEFAULTS_PROPERTY     TYPE /BOBF/OBM_NODE_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C42CE1A',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_HR231_DEFAULTS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PERNR                          TYPE STRING VALUE 'PERNR',
  EMERGROLE_ID                   TYPE STRING VALUE 'EMERGROLE_ID',
  KZ                             TYPE STRING VALUE 'KZ',
  EN                             TYPE STRING VALUE 'EN',
  RU                             TYPE STRING VALUE 'RU',
      END OF ZC_HR231_DEFAULTS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_HR231_DEFAULTS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '495EFABCCEFB1EDDABD4A5BA9C41AE1A',
      END OF ZC_HR231_DEFAULTS,
    END OF SC_NODE_CATEGORY .
endinterface.
